[build]
command = "npm run build"
publish = "/build"
base = "/"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "http://localhost:10000/api"
status = 200
